# Generated by Django 5.2.11 on 2026-02-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_user_business_name_user_experience_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="phone number"
                    ),
                ),
                ("otp", models.CharField(max_length=6, verbose_name="OTP code")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login_2fa", "Login 2FA"),
                            ("phone_verify", "Phone Verification"),
                        ],
                        default="login_2fa",
                        max_length=20,
                        verbose_name="purpose",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires at"
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS OTP",
                "verbose_name_plural": "SMS OTPs",
                "db_table": "sms_otps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_2fa_enabled",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp_secret",
        ),
        migrations.AddField(
            model_name="user",
            name="is_phone_verified",
            field=models.BooleanField(default=False, verbose_name="phone verified"),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="TOTP secret"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret_pending",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="pending TOTP secret"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="two_fa_method",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("totp", "Authenticator App (TOTP)"),
                    ("sms", "SMS OTP"),
                ],
                default="disabled",
                max_length=10,
                verbose_name="2FA method",
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expires at"
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("email_verification", "Email Verification"),
                    ("password_reset", "Password Reset"),
                ],
                default="email_verification",
                max_length=30,
                verbose_name="purpose",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="phone number"
            ),
        ),
    ]
